name: Deploy to Production

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Debug Environment Variables
        run: |
          echo "ECR_REPO_URI=${ECR_REPO_URI}"
          echo "IMAGE_TAG=${IMAGE_TAG}"

      - name: Check Docker Version
        run: docker --version

      - name: Build Docker Image
        env:
          ECR_REPO_URI: public.ecr.aws/t0s1o0r9/bank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --progress=plain -t $ECR_REPO_URI:$IMAGE_TAG .

      - name: Push Docker Image
        env:
          ECR_REPO_URI: public.ecr.aws/t0s1o0r9/bank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REPO_URI:$IMAGE_TAG
